---
- hosts: public
  name: Public web servers
  user: ubuntu

  pre_tasks:
  - name: Updating and upgrading packages
    become: true
    raw: apt -yq update && apt -yq upgrade
    changed_when: false

  # Package is needed to allow non-root tasks to work
  # https://github.com/georchestra/ansible/issues/55
  - name: Installing acl
    become: true
    apt:
      name: acl
      update_cache: true

  - name: Installing Python
    become: true
    apt:
      name: 
      - python3=3.8.2-0ubuntu2
      - python3-pip=20.0.2-5ubuntu1.1
      update_cache: true

  tasks:
  - name: Installing NGINX
    become: true
    apt:
      name: nginx=1.18.0-0ubuntu1
      update_cache: true

  - name: Installing Python tools
    become: true
    pip:
      name:
      - virtualenv
      - supervisor
      - uwsgi

  - name: Create test application service account group
    become: true
    group:
      name: test-application
      state: present
      gid: 1405

  - name: Adding test application service account
    become: true
    user:
      name: test-application
      comment: Service account for the test application
      create_home: false
      state: present
      uid: 1405
      group: test-application

  - name: Adding test application group to NGINX user
    become: true
    user:
      name: www-data
      groups:
      - test-application
      append: true

  - name: Create test application server directory
    become: true
    file:
      path: /srv/test-application
      state: directory
      owner: test-application
      group: test-application
      mode: '0770'

  - name: Create test application virtualenv directory
    become: true
    file:
      path: /srv/test-application/venv
      state: directory
      owner: test-application
      group: test-application
      mode: '0770'

  - name: Copy test application
    become: true
    copy:
      owner: test-application
      group: test-application
      mode: '0640'
      src: ./../test-application
      dest: /srv

  - name: Install test application dependencies
    become: true
    become_user: test-application
    pip:
      requirements: /srv/test-application/requirements.txt
      virtualenv: /srv/test-application/venv
  
  - name: Auto clean
    become: true
    apt:
      autoclean: yes

  - name: Auto remove
    become: true
    apt:
      autoremove: yes
