---
- hosts: public
  name: Public web servers
  user: ubuntu

  pre_tasks:
  - name: Updating and upgrading packages
    become: true
    raw: apt -yq update && apt -yq upgrade
    changed_when: false

  # Package is needed to allow non-root tasks to work
  # https://github.com/georchestra/ansible/issues/55
  - name: Installing acl
    become: true
    apt:
      name: acl

  - name: Installing Python
    become: true
    apt:
      name: 
      - python3=3.8.2-0ubuntu2
      - python3-pip=20.0.2-5ubuntu1.1

  tasks:
  - name: Modifying hard nofile PAM limits
    become: true
    community.general.pam_limits:
      domain: '*'
      limit_type: hard
      limit_item: nofile
      value: '65535'

  - name: Modifying soft nofile PAM limits
    become: true
    community.general.pam_limits:
      domain: '*'
      limit_type: soft
      limit_item: nofile
      value: '65535'

  - name: Installing NGINX
    become: true
    apt:
      name: nginx=1.18.0-0ubuntu1

  - name: Installing required packages
    become: true
    apt:
      name:
      - ntp=1:4.2.8p12+dfsg-3ubuntu4
      - telnet=0.17-41.2build1
      - mtr=0.93-1
      - tree=1.8.0-1
      # Because I like this tool
      - glances=3.1.3-1

  - name: Installing Python tools
    become: true
    pip:
      name:
      - virtualenv==20.0.35

  - name: Creating test application service account group
    become: true
    group:
      name: test-application
      state: present
      gid: 1405

  - name: Adding test application service account
    become: true
    user:
      name: test-application
      comment: Service account for the test application
      create_home: false
      state: present
      uid: 1405
      group: test-application

  - name: Adding test application group to NGINX user
    become: true
    user:
      name: www-data
      groups:
      - test-application
      append: true

  - name: Creating test application server directory
    become: true
    file:
      path: /srv/test-application
      state: directory
      owner: test-application
      group: test-application
      mode: '0770'

  - name: Creating test application virtualenv directory
    become: true
    file:
      path: /srv/test-application/venv
      state: directory
      owner: test-application
      group: test-application
      mode: '0770'

  - name: Copying test application
    become: true
    copy:
      owner: test-application
      group: test-application
      mode: '0640'
      src: ./../test-application
      dest: /srv

  - name: Installing test application dependencies
    become: true
    become_user: test-application
    pip:
      requirements: /srv/test-application/requirements.txt
      virtualenv: /srv/test-application/venv

  - name: Installing test application Python dependencies
    become: true
    become_user: test-application
    pip:
      requirements: /srv/test-application/requirements.txt
      virtualenv: /srv/test-application/venv
      state: latest

  - name: Deleting default NGINX config
    become: true
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Copying test application NGINX config
    become: true
    template:
      owner: test-application
      group: test-application
      mode: '0644'
      src: ./test-application-nginx.conf
      dest: /etc/nginx/sites-enabled

  - name: Restarting NGINX systemd service
    become: true
    service:
      name: nginx
      state: restarted

  - name: Copying test application systemd service
    become: true
    template:
      owner: test-application
      group: test-application
      mode: '0644'
      src: ./test-application.service
      dest: /lib/systemd/system

  - name: Reloading systemd daemon
    become: true
    systemd:
      daemon_reload: yes

  - name: Starting test application service
    become: true
    service:
      name: test-application
      state: started
  
  - name: Auto cleaning Ubuntu packages
    become: true
    apt:
      autoclean: yes

  - name: Auto removing Ubuntu packages
    become: true
    apt:
      autoremove: yes
